# Generated by Django 3.1.4 on 2020-12-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='profile_image',
            field=models.ImageField(upload_to='user_profile_images'),
        ),
    ]
