# Generated by Django 3.1.4 on 2020-12-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201210_2014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='UserInfo',
        ),
    ]
