# Generated by Django 3.1.4 on 2020-12-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201211_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.TextField(default=''),
        ),
    ]
