# Generated by Django 3.1.4 on 2020-12-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201211_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secrets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField(default='')),
                ('username', models.CharField(max_length=11)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
