# Generated by Django 3.1.4 on 2020-12-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201212_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secrets',
            old_name='username',
            new_name='by',
        ),
    ]
